custom_rules:
  - profiles/wadoh/wa_filter.smk

#builds_to_run: ["genome", "G", "F"]
builds_to_run: ["genome"]

#resolutions_to_run: ["all-time", "6y", "3y"]
resolutions_to_run: ["all-time"]


filter:
  group_by: "year country division"

  subsample_max_sequences:
    genome: 10000

  # NOTE: these are unused; see filters applied directly in wa_filter.smk
  subsampling:
    state: 'division == "Washington" '
    country: 'division != "Washington" '

files:
  auspice_config: "profiles/wadoh/auspice_config_wa.json"
