custom_rules:
  - "profiles/wadoh/wa_filter.smk"

builds_to_run: ["genome"]

resolutions_to_run: ["6y"]

filter:
  group_by: "year country division"

files:
  auspice_config: "profiles/wadoh/auspice_config_wa.json"
