samples:
  recent:
    exclude: config/outliers_ppx.txt
    exclude_where:
    - qc.overallStatus=bad
    group_by:
    - year
    - country
    min_length: 600
    query: G_coverage>0.3 & missing_data<1000
    min_date: 6Y
    max_sequences: 3000
  background:
    exclude: config/outliers_ppx.txt
    exclude_where:
    - qc.overallStatus=bad
    - qc.overallStatus=mediocre
    group_by:
    - year
    - country
    min_length: 600
    query: G_coverage>0.3 & missing_data<1000
    max_date: 6Y
    max_sequences: 300
