samples:
  all-time:
    exclude: config/outliers_ppx.txt
    exclude_where:
    - qc.overallStatus=bad
    group_by:
    - year
    - country
    min_length: 10000
    query: genome_coverage>0.3 & missing_data<1000
    min_date: 1975-01-01
    max_sequences: 3000
