
configfile: "config/config.yaml"

rule all:
    input:
        "data/a/sequences.fasta",
        "data/a/metadata.tsv",
        "data/b/sequences.fasta",
        "data/b/metadata.tsv",
        "data/a/sequences_open.fasta",
        "data/a/metadata_open.tsv",
        "data/b/sequences_open.fasta",
        "data/b/metadata_open.tsv",
        "data/a/sequences_restricted.fasta",
        "data/a/metadata_restricted.tsv",
        "data/b/sequences_restricted.fasta",
        "data/b/metadata_restricted.tsv",


include: "workflow/snakemake_rules/fetch_sequences.smk"
include: "workflow/snakemake_rules/curate.smk"
include: "workflow/snakemake_rules/sort.smk"

if "custom_rules" in config:
    for rule_file in config["custom_rules"]:
        include: rule_file
