# Sources of sequences to include in the ingest run
sources: ['genbank']
conda_environment: "workflow/envs/nextstrain.yaml"
fetch:
  genbank_url:
    a: "https://www.ncbi.nlm.nih.gov/genomes/VirusVariation/vvsearch2/?fq=%7B%21tag%3DSeqType_s%7DSeqType_s%3A%28%22Nucleotide%22%29&fq=VirusLineageId_ss%3A%28208893%29&q=%2A%3A%2A&cmd=download&dlfmt=csv&fl=genbank_accession%3Aid%2Cgenbank_accession_rev%3AAccVer_s%2Cdatabase%3ASourceDB_s%2Cstrain%3AIsolate_s%2Cregion%3ARegion_s%2Clocation%3ACountryFull_s%2Ccollected%3ACollectionDate_s%2Csubmitted%3ACreateDate_dt%2Clength%3ASLen_i%2Chost%3AHost_s%2Cisolation_source%3AIsolation_csv%2Cbioproject_accession%3ABioProject_s%2Cbiosample_accession%3ABioSample_s%2Csra_accession%3ASRALink_csv%2Ctitle%3ADefinition_s%2Cauthors%3AAuthors_csv%2Cpublications%3APubMed_csv%2Csequence%3ANucleotide_seq&sort=SourceDB_s+desc%2C+CollectionDate_s+asc%2C+id+asc&email=hello%40nextstrain.org"
    b: "https://www.ncbi.nlm.nih.gov/genomes/VirusVariation/vvsearch2/?fq=%7B%21tag%3DSeqType_s%7DSeqType_s%3A%28%22Nucleotide%22%29&fq=VirusLineageId_ss%3A%28208895%29&q=%2A%3A%2A&cmd=download&dlfmt=csv&fl=genbank_accession%3Aid%2Cgenbank_accession_rev%3AAccVer_s%2Cdatabase%3ASourceDB_s%2Cstrain%3AIsolate_s%2Cregion%3ARegion_s%2Clocation%3ACountryFull_s%2Ccollected%3ACollectionDate_s%2Csubmitted%3ACreateDate_dt%2Clength%3ASLen_i%2Chost%3AHost_s%2Cisolation_source%3AIsolation_csv%2Cbioproject_accession%3ABioProject_s%2Cbiosample_accession%3ABioSample_s%2Csra_accession%3ASRALink_csv%2Ctitle%3ADefinition_s%2Cauthors%3AAuthors_csv%2Cpublications%3APubMed_csv%2Csequence%3ANucleotide_seq&sort=SourceDB_s+desc%2C+CollectionDate_s+asc%2C+id+asc&email=hello%40nextstrain.org"
    general: "https://www.ncbi.nlm.nih.gov/genomes/VirusVariation/vvsearch2/?fq=%7B%21tag%3DSeqType_s%7DSeqType_s%3A%28%22Nucleotide%22%29&fq=VirusLineageId_ss%3A%2811250%29&q=%2A%3A%2A&cmd=download&dlfmt=csv&fl=genbank_accession%3Aid%2Cgenbank_accession_rev%3AAccVer_s%2Cdatabase%3ASourceDB_s%2Cstrain%3AIsolate_s%2Cregion%3ARegion_s%2Clocation%3ACountryFull_s%2Ccollected%3ACollectionDate_s%2Csubmitted%3ACreateDate_dt%2Clength%3ASLen_i%2Chost%3AHost_s%2Cisolation_source%3AIsolation_csv%2Cbioproject_accession%3ABioProject_s%2Cbiosample_accession%3ABioSample_s%2Csra_accession%3ASRALink_csv%2Ctitle%3ADefinition_s%2Cauthors%3AAuthors_csv%2Cpublications%3APubMed_csv%2Csequence%3ANucleotide_seq&sort=SourceDB_s+desc%2C+CollectionDate_s+asc%2C+id+asc&email=hello%40nextstrain.org"

# Params for the transform rulegeneral
transform:
  # Fields to rename.
  # This is the first step in the pipeline, so any references to field names
  # in the configs below should use the new field names
  field_map: ['collected=date', 'submitted=date_submitted', 'genbank_accession=accession']
  # Standardized strain name regex
  # Currently accepts any characters because we do not have a clear standard for strain names
  strain_regex: '^.+$'
  # Back up strain name field if 'strain' doesn't match regex above
  strain_backup_fields: ['accession']
  # List of date fields to standardize
  date_fields: ['date', 'date_submitted']
  # Expected date formats present in date fields
  # These date formats should use directives expected by datetime
  # See https://docs.python.org/3.9/library/datetime.html#strftime-and-strptime-format-codes
  expected_date_formats: ['%Y', '%Y-%m', '%Y-%m-%d', '%Y-%m-%dT%H:%M:%SZ']
  # Titlecase rules
  titlecase:
    # Abbreviations not cast to titlecase, keeps uppercase
    abbreviations: ['USA']
    # Articles that should not be cast to titlecase
    articles: [
      'and', 'd', 'de', 'del', 'des', 'di', 'do', 'en', 'l', 'la', 'las', 'le',
      'los', 'nad', 'of', 'op', 'sur', 'the', 'y'
    ]
    # List of string fields to titlecase
    fields: ['region', 'country', 'division', 'location']
  # Authors field name
  authors_field: 'authors'
  # Authors default value if authors value is empty
  authors_default_value: '?'
  # Field name for the generated abbreviated authors
  abbr_authors_field: 'abbr_authors'
  # General geolocation rules to apply to geolocation fields
  geolocation_rules_url: 'https://raw.githubusercontent.com/nextstrain/ncov-ingest/master/source-data/gisaid_geoLocationRules.tsv'
  # Local geolocation rules that are only applicable to rsv data
  # Local rules can overwrite the general geolocation rules provided above
  local_geolocation_rules: 'source-data/geolocation-rules.tsv'
  # User annotations file
  annotations: 'source-data/annotations.tsv'
  # ID field used to merge annotations
  annotations_id: 'accession'
  # Field to use as the sequence ID in the FASTA file
  id_field: 'accession'
  # Field to use as the sequence in the FASTA file
  sequence_field: 'sequence'
  # Final output columns for the metadata TSV
  metadata_columns: [
    'accession',
    'genbank_accession_rev',
    'strain',
    'date',
    'region',
    'country',
    'division',
    'location',
    'host',
    'date_submitted',
    'sra_accession',
    'abbr_authors',
    'reverse',
    'authors',
    'institution'
  ]

upload:
  s3:
    # AWS S3 Bucket with prefix
    dst: 's3://nextstrain-data/files/workflows/rsv'
    # Files to upload to S3 that are in the `data` directory
    files_to_upload: [
      'a/metadata.tsv',
      'a/sequences.fasta',
      'b/metadata.tsv',
      'b/sequences.fasta'
    ]
    # Remote file names for the files to upload, must be in the same order as local files above
    remote_file_names: [
      'a/metadata.tsv.gz',
      'a/sequences.fasta.xz',
      'b/metadata.tsv.gz',
      'b/sequences.fasta.xz'
    ]
    cloudfront_domain: 'data.nextstrain.org'
