# Subsample configuration using N-dimensional format
# Format: base → params (by dimension) → dimensions (Cartesian product)

# Base parameters applied to all builds
base:
  exclude: "config/outliers_ppx.txt"
  exclude_where:
    - qc.overallStatus=bad
  group_by:
    - year
    - country

output_name_template: "{build}_{resolution}"

# Dimension-specific parameters
# Order of dimensions matters for merge precedence
params:
  build:
    genome:
      min_length: 10000
      query: genome_coverage>0.3 & missing_data<1000
    G:
      min_length: 600
      query: G_coverage>0.3 & missing_data<1000
    F:
      min_length: 1200
      query: F_coverage>0.3 & missing_data<1000

  resolution:
    all-time:
      samples:
        all-time:
          min_date: 1975-01-01
          max_sequences: 3000
    6y:
      samples:
        recent:
          min_date: 6Y
          max_sequences: 3000
        background:
          max_date: 6Y
          max_sequences: 300
          exclude_where:
            - qc.overallStatus=bad
            - qc.overallStatus=mediocre
    3y:
      samples:
        recent:
          min_date: 3Y
          max_sequences: 3000
        background:
          max_date: 3Y
          max_sequences: 300
          exclude_where:
            - qc.overallStatus=bad
            - qc.overallStatus=mediocre
