#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CUE_DIR="$REPO_ROOT/cue"
CONFIG_FILE="$REPO_ROOT/config/configfile.yaml"
SCHEMA_FILE="$REPO_ROOT/config.schema.yaml"
DOCS_FILE="$REPO_ROOT/config/README.md"

echo "Validating CUE configuration and schema..."
cue vet "$CUE_DIR"

echo "Generating $CONFIG_FILE..."
(
    echo "# [DO NOT EDIT] This file was generated by CUE (cue/)."
    cue export "$CUE_DIR" --out yaml
) > "$CONFIG_FILE"

echo "Generating $SCHEMA_FILE..."
(
    echo "# [DO NOT EDIT] This file was generated by CUE (cue/)."
    cue export "$CUE_DIR" --out jsonschema -e '#Config' | cue export json: - --out yaml
) > "$SCHEMA_FILE"

echo "Generating $DOCS_FILE..."
nextstrain shell "$REPO_ROOT" -c "python3 scripts/generate_docs.py config.schema.yaml config/configfile.yaml" > "$DOCS_FILE"

echo "Done! Successfully generated:"
echo "  - $CONFIG_FILE"
echo "  - $SCHEMA_FILE"
echo "  - $DOCS_FILE"
