#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CUE_DIR="$REPO_ROOT/cue"
CONFIG_FILE="$REPO_ROOT/config/configfile.yaml"
SCHEMA_FILE="$REPO_ROOT/config.schema.yaml"
DOCS_FILE="$REPO_ROOT/config/README.md"
PYTHON="${PYTHON:-/usr/bin/python3}"

echo "Validating CUE configuration and schema..."
cue vet "$CUE_DIR"

echo "Generating $CONFIG_FILE..."
(
    echo "# [DO NOT EDIT] This file was generated by CUE (cue/)."
    cue export "$CUE_DIR" --out yaml
) > "$CONFIG_FILE"

echo "Generating $SCHEMA_FILE..."
# Options for subsample config schema (and Augur schemas in general):
# 1. Reference by URL. This mimics the existing config schema, and the URL
#    reference allows local Augur to resolve to its own schema (version may
#    differ from remote). Downside is we need a hack like below, which can get
#    unwieldy with more Augur config schemas.
# 2. Inline the subsample config schema when generating the config schema file.
#    This would be best with "workflows as programs" work where the exact Augur
#    version is bundled closely with the workflow code, but that's far away...
(
    echo "# [DO NOT EDIT] This file was generated by CUE (cue/)."
    cue export "$CUE_DIR" --out jsonschema -e '#Schema' | "$PYTHON" -c '
import sys, json

data = json.load(sys.stdin)
schema_url = "https://nextstrain.org/schemas/augur/subsample-config-unaligned/v1"

for prop in ["subsample", "custom_subsample"]:
    if prop in data.get("properties", {}):
        data["properties"][prop]["additionalProperties"]["$ref"] = schema_url

for key in ["SubsampleConfigUnaligned", "defaultProperties", "filterSampleProperties"]:
    data.get("$defs", {}).pop(key, None)

json.dump(data, sys.stdout)
' | cue export json: - --out yaml
) > "$SCHEMA_FILE"

echo "Generating $DOCS_FILE..."
"$PYTHON" "$REPO_ROOT/scripts/generate_docs.py" "$SCHEMA_FILE" "$CONFIG_FILE" > "$DOCS_FILE"

echo "Done."
