name: Rebuild RSV analysis

on:
  schedule:
    # Note times are in UTC, which is 1 or 2 hours behind CET depending on daylight savings.
    #
    # Note the actual runs might be late.
    # Numerous people were confused, about that, including me:
    #  - https://github.community/t/scheduled-action-running-consistently-late/138025/11
    #  - https://github.com/github/docs/issues/3059
    #
    # Note, '*' is a special character in YAML, so you have to quote this string.
    #
    # Docs:
    #  - https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#schedule
    #
    # Tool that deciphers this particular format of crontab string:
    #  - https://crontab.guru/
    #
    # Runs at 4pm UTC (12pm EDT) since curation by NCBI happens on the East Coast.
    - cron:  '0 19 * * 2'

  repository_dispatch:
    types:
      - rebuild

  workflow_dispatch:
    inputs:
      trial_name:
        description: |
          Trial name for deploying builds.
          If not set, builds will overwrite existing builds at s3://nextstrain-data/rsv*
          If set, builds will be deployed to s3://nextstrain-staging/rsv_trials_<trial_name>_*
        required: false
        type: string
jobs:
  rebuild_rsv:
    permissions:
      id-token: write
    uses: nextstrain/.github/.github/workflows/pathogen-repo-build.yaml@master
    secrets: inherit
    with:
      runtime: aws-batch
      env: |
        TRIAL_NAME: ${{ inputs.trial_name }}
      run: |
        declare -a config

        if [[ "$TRIAL_NAME" ]]; then
          config+=("deploy_url=s3://nextstrain-staging/rsv_trials_${TRIAL_NAME}_")
        fi

        nextstrain build \
          --aws-batch \
          --detach \
          --no-download \
          --cpus 16 \
          --memory 64gib \
          . \
          deploy \
            --configfiles config/configfile.yaml config/nextstrain_automation.yaml \
            --config "${config[@]}"
